import { AxiosResponse } from "axios";
import { fetchCategories } from "@/http";

import { ICategory, ICollectionResponse } from "@/types";
import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Edxplore</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="text-primary-900">Welcome to Code Blog!</h1>
      </main>
    </div>
  );
};

export const getServerSideProps: GetServerSideProps = async () => {
  //categories
  const {
    data: categories,
}: AxiosResponse<ICollectionResponse<ICategory[]>> =
    await fetchCategories();


  return {
    props: {
      categories: {
        items: categories.data,
      },
    },
  };
};
export default Home;
